
language: python
python:
  - 3.8

cache: pip

install:
  - pip install --upgrade pip
  - pip install --upgrade -r test-requirements.txt
  - pip install --upgrade pre-commit

env:
 - JZMQ_SKIP_INET6_PORT_CHECKS=1

script:
  - ip addr show
  - pre-commit run -a
